CREATE TABLE Inventory (
    INVENTORY_QUANTITY INT NOT NULL,
    PRODUCT_SKU BIGINT NOT NULL,
    LOCATION_ID INT NOT NULL,
    PRIMARY KEY (PRODUCT_SKU, LOCATION_ID),
    FOREIGN KEY (PRODUCT_SKU) REFERENCES Product(PRODUCT_SKU),
    FOREIGN KEY (LOCATION_ID) REFERENCES Location(LOCATION_ID)
);

CREATE TABLE Invoice (
    INVOICE_ID INT NOT NULL AUTO_INCREMENT,
    INVOICE_DATE DATE NOT NULL,
    INVOICE_TOTAL DECIMAL(10, 2) NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PRIMARY KEY (INVOICE_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer(CUSTOMER_ID)
);

DELIMITER //
CREATE TRIGGER UpdateInvoiceTotal
AFTER INSERT ON Transaction
FOR EACH ROW
BEGIN
    UPDATE Invoice
    SET INVOICE_TOTAL = (
        SELECT SUM(t.Quantity * t.Transaction_Price)
        FROM Transaction t
        WHERE t.INVOICE_ID = NEW.INVOICE_ID
    )
    WHERE INVOICE_ID = NEW.INVOICE_ID;
END;
//
DELIMITER ;

INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-03-10', 2);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-05', 16);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-03-03', 4);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-03-23', 17);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-28', 20);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-11', 1);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-29', 19);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-12-10', 12);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-22', 10);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-11-19', 15);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-03-16', 6);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-01-25', 20);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-11-08', 6);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-10', 19);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-01-11', 13);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-03-07', 7);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-07-27', 19);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-03-14', 16);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-07-19', 2);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-04-03', 19);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-05', 6);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-07-06', 19);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-05-19', 10);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-01-02', 18);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-29', 8);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-10-12', 5);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-18', 8);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-26', 11);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-11-30', 2);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-05-25', 10);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-13', 4);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-01-18', 18);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-05-05', 2);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-09-08', 12);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-09-24', 2);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-09-17', 20);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-01-29', 15);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-22', 15);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-04-03', 20);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-05-25', 5);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-12-14', 1);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-15', 6);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-12', 10);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-04-08', 5);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-09', 19);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-10-11', 1);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-26', 17);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-03-18', 14);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-05-04', 19);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-15', 6);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-10-19', 1);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-09-07', 11);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-04-23', 5);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-30', 18);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-26', 9);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-01-05', 3);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-12-04', 16);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-07-04', 17);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-05-24', 14);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-11-21', 2);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-10-03', 10);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-03-21', 1);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-05-21', 10);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-01-04', 18);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-05-29', 15);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-03', 13);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-10-24', 11);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-01-19', 6);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-12-13', 13);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-28', 20);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-03-21', 10);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-01-14', 20);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-09', 8);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-14', 3);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-29', 12);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-14', 9);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-04-15', 2);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-05-13', 5);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-22', 13);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-04-03', 14);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-28', 7);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-09-18', 6);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-10-25', 4);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-06-16', 16);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-09-06', 18);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-04-18', 2);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-02-28', 11);
INSERT INTO Invoice (INVOICE_DATE, CUSTOMER_ID) VALUES ('2024-08-10', 5);


INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (201, 1037, 7);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (59, 1019, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (466, 1055, 3);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (199, 1008, 2);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (498, 1029, 7);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (265, 1053, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (57, 1041, 3);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (392, 1002, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (237, 1010, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (119, 1040, 1);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (105, 1043, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (179, 1036, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (470, 1095, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (235, 1001, 3);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (229, 1046, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (326, 1096, 2);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (442, 1047, 1);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (392, 1074, 7);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (291, 1074, 7);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (461, 1049, 9);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (187, 1036, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (355, 1073, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (455, 1080, 2);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (471, 1086, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (63, 1051, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (495, 1007, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (56, 1027, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (274, 1080, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (392, 1071, 5);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (46, 1082, 1);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (73, 1086, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (125, 1096, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (135, 1003, 10);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (400, 1090, 2);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (428, 1022, 9);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (12, 1059, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (370, 1067, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (174, 1080, 5);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (203, 1051, 5);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (384, 1026, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (251, 1073, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (375, 1020, 1);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (218, 1071, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (102, 1016, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (193, 1078, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (1, 1087, 10);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (323, 1085, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (494, 1049, 9);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (335, 1061, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (80, 1074, 10);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (14, 1039, 2);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (11, 1070, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (353, 1033, 9);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (317, 1002, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (69, 1080, 2);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (264, 1095, 9);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (71, 1079, 3);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (424, 1052, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (459, 1046, 3);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (147, 1037, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (157, 1077, 1);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (412, 1002, 3);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (244, 1066, 9);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (481, 1089, 5);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (60, 1064, 3);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (489, 1001, 2);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (389, 1067, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (148, 1081, 7);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (17, 1045, 1);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (45, 1029, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (292, 1082, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (255, 1020, 10);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (415, 1045, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (146, 1024, 7);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (27, 1036, 5);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (469, 1033, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (177, 1056, 5);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (316, 1088, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (337, 1037, 8);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (246, 1077, 10);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (151, 1018, 3);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (107, 1033, 10);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (39, 1040, 10);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (460, 1097, 1);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (277, 1083, 9);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (359, 1084, 7);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (483, 1052, 5);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (437, 1043, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (253, 1024, 9);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (411, 1039, 7);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (323, 1007, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (92, 1003, 4);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (134, 1097, 7);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (179, 1009, 6);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (113, 1046, 2);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (467, 1069, 2);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (148, 1040, 9);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (313, 1074, 1);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (330, 1048, 3);
INSERT INTO Inventory (INVENTORY_QUANTITY, PRODUCT_SKU, LOCATION_ID) VALUES (69, 1056, 9);




